repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix", "--show-fixes"]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: generate-github-workflows
        name: generate-github-workflows
        entry: tox
        args: ["-e", "generate-workflows"]
        language: python
        additional_dependencies:
          - tox
        types: [file]
        files: tox.ini
        pass_filenames: false
