name: Core Contrib Test

on:
  push:
    branches-ignore:
    - 'release/*'
  pull_request:

jobs:
  core_contrib_0:
    name: opentelemetry-python-contrib
    uses: emdneto/opentelemetry-python-contrib/.github/workflows/core_contrib_test_0.yml@generate-workflows-core
    with:
      CORE_REPO_SHA: ${{ github.sha }}
