name: Core Contrib Test

on:
  push:
    branches-ignore:
    - 'release/*'
  pull_request:

env:
  CORE_REPO_SHA: ${{ github.sha }}
  CONTRIB_REPO_SHA: main
  PIP_EXISTS_ACTION: w

jobs:
  contrib_0:
    uses: open-telemetry/opentelemetry-python-contrib/.github/workflows/core_contrib_test_0.yml@main
    with:
      CORE_REPO_SHA: ${{ env.CORE_REPO_SHA }}
      CONTRIB_REPO_SHA: ${{ env.CONTRIB_REPO_SHA }}
